rwi/frontend/urls.py
from django.urls import path
from .views import *

app_name = "frontend"
urlpatterns = [
    path('', index, name='index'),
    path("campaigns/", campaign, name="campaign"),
    path("campaign/<str:slug>", campaign_detail, name="campaign_detail"),
    path("news/", news, name="news"),
    path("news/<str:slug>", news_detail, name="news_detail"),
    path("videos/", videos, name="videos"),
    path("videos/<str:slug>", videos_detail, name="videos_detail"),
    path("publications/", publications, name="publications"),
    path("gallery/", gallery, name="gallery"),
    path("gallery/<str:slug>", gallery_detail, name="gallery_detail"),
    path("lazy-load-news/", lazy_load_news, name="lazy_load_news"),
    path("search-publication/", search_publication, name="search_publication"),
    path("search/", search, name="search"),
    path("subscribe/", subscribe, name="subscribe"),
    path('lazy-load-photo/<int:id>', lazy_load_photo, name='lazy_load_photo'),
]

rwi/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

admin.site.site_header = "RWI Admin"
admin.site.site_title = "RWI Admin Portal"
admin.site.index_title = "Welcome to RWI Admin Portal"

urlpatterns = [
    path('rwi-admin/', admin.site.urls),
    path('', include('rwi.frontend.urls', namespace='frontend')),
    path('summernote/', include('django_summernote.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# di server saat settings debug true
if settings.DEBUG:
    urlpatterns + static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

rwi/apps/content/models.py
from rwi.core.utils import FilenameGenerator, custom_slugify
from django.db import models

class Banner(models.Model):
    class Meta:
        verbose_name = 'Home Banner'
        verbose_name_plural = 'Home Banner'

    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))
    big_text = models.CharField(max_length=254, blank=True, null=True)
    small_text = models.CharField(max_length=254, blank=True, null=True)
    video_url = models.CharField(max_length=254, blank=True, null=True)
    find_out_url = models.CharField(max_length=100, blank=True, null=True)
    hastag = models.CharField(max_length=254, blank=True, null=True)
    is_active = models.BooleanField(default=True, blank=True, null=True)
    # base_color = models.CharField("RGBA Color", max_length=20, null=True, help_text='ex: rgba(5,197,214,1)')
    
    def __str__(self):
        return f"{self.id}"
    
class Tag(models.Model):
    name = models.CharField(max_length=32)

    def __str__(self):
        return self.name

class Videos(models.Model):
    class Meta:
        verbose_name = 'Video'
        verbose_name_plural = 'Video'

    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='banner'))
    video_url = models.CharField(max_length=254)
    title = models.CharField(max_length=254)
    time = models.CharField(max_length=254)
    slug = models.CharField(unique=True, blank=True, max_length=254)
    tags = models.ManyToManyField(Tag)
    date = models.DateField(auto_now_add=True)
    long_desc = models.TextField("The Story Behind", null=True)
    is_active = models.BooleanField("Published", default=True)
    is_featured = models.BooleanField("Featured", default=True)
    date = models.DateField()

    def __str__(self):
        return self.title

    @property
    def model_name(self):
        return 'video'

    @property
    def short_desc(self):
        return self.long_desc

    def preview(self):
        return mark_safe('<a href="/blog/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Videos, self).save()



class News(models.Model):
    class Meta:
        verbose_name = 'News'
        verbose_name_plural = 'News'

    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    title = models.CharField(max_length=254)
    date = models.DateField()
    short_desc = models.CharField(max_length=254)
    long_desc = models.TextField()
    is_active = models.BooleanField("Published", default=True)
    is_featured = models.BooleanField("Featured", default=True)
    slug = models.CharField(unique=True, blank=True, max_length=254)
    tags  = models.ManyToManyField(Tag)
    author = models.ForeignKey('user.User', on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.title

    def preview(self):
        return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(News, self).save()
    
    @property
    def model_name(self):
        return 'news'


class Campaign(models.Model):
    class Meta:
        verbose_name = 'Campaign'
        verbose_name_plural = 'Campaign'

    img =  models.ImageField(upload_to=FilenameGenerator(
        prefix='campaign'))
    img2 =  models.ImageField(upload_to=FilenameGenerator(
        prefix='campaign'))
    title = models.CharField(max_length=254)
    hastag = models.CharField(max_length=254)
    short_desc = models.TextField(max_length=254, null=True)
    long_desc = models.TextField(null=True)
    is_featured = models.BooleanField("Featured", default=True)
    video = models.ForeignKey('content.videos', on_delete=models.SET_NULL, null=True)
    base_color = models.CharField("Hex Color", max_length=20)
    slug = models.CharField(unique=True, blank=True, max_length=254, null=True)
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Campaign, self).save()


class Publication(models.Model):
    class Meta:
        verbose_name = 'Publication'
        verbose_name_plural = 'Publication'

    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='banner'))
    title = models.CharField(max_length=254)
    date = models.DateField()
    short_desc = models.CharField(max_length=254)
    long_desc = models.TextField()
    is_active = models.BooleanField("Published", default=True)
    slug = models.CharField(unique=True, blank=True, max_length=254)
    file =  models.FileField("File", upload_to=FilenameGenerator(
        prefix='publication'), null=True)
    
    def __str__(self):
        return self.title

    def preview(self):
        return mark_safe('<a href="/news/%s" target="_blank"/> preview </a>' % self.slug)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Publication, self).save()
    
    @property
    def model_name(self):
        return 'publication'



class Album(models.Model):
    class Meta:
        verbose_name = 'Gallery'
        verbose_name_plural = 'Gallery'

    title = models.CharField("Name", max_length=255)
    slug = models.CharField(unique=True, blank=True, max_length=254)
    is_active = models.BooleanField("Published", default=True)
    img =  models.ImageField("Cover Album", upload_to=FilenameGenerator(
        prefix='album'))
    
    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = custom_slugify(self.title)
        super(Album, self).save()


class Photo(models.Model):
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photo'

    img =  models.ImageField("image", upload_to=FilenameGenerator(
        prefix='photo'))
    album = models.ForeignKey('content.Album', on_delete=models.CASCADE)
    is_featured = models.BooleanField("Featured", default=False)
    long_desc = models.CharField("Featured Description", max_length=255, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    
    def __str__(self):
        return f'{self.album.title}-{self.id}' 

rwi/frontend/forms.py
# from rwi.apps.contactus.models import Contactus
# from django import forms


# class ContactusForm(forms.ModelForm):
#     class Meta:
#         model = Contactus
#         fields = '__all__'

rwi/apps/content/views.py
from django.shortcuts import render

# Create your views here.

rwi/apps/settings/views.py
from django.shortcuts import render

# Create your views here.

rwi/apps/subscribe/views.py
from django.shortcuts import render

# Create your views here.

rwi/apps/user/views.py
from django.shortcuts import render

# Create your views here.

rwi/frontend/views.py
import json
from django.http import JsonResponse
from django.template.response import TemplateResponse
from django.template import loader
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt

from rwi.apps.content.models import *
from rwi.apps.settings.models import *
from rwi.apps.subscribe.models import *

from rwi.core.serializer import serialize_settings

from django.db.models import Q

# from .forms import ContactusForm


def index(request):
    context = {
        "banners" : Banner.objects.filter(is_active=True).order_by('-id'),
        "latest_videos" : Videos.objects.filter(is_active=True).order_by('-id'),
        "latest_news" : News.objects.filter(is_active=True).order_by('-id').all(),
        "f_video": Videos.objects.filter(is_featured=True).order_by('-id').first(),
        "settings":  get_settings(),
        "featured_photos": Photo.objects.filter(is_featured=True).order_by('-id').all()[:10]
    }
    return TemplateResponse(request, 'frontend/index.html', context)

def campaign(request):
    campaigns = Campaign.objects.all()
    return TemplateResponse(request, 'frontend/campaign.html', {
        "campaigns": campaigns,
        "settings":  get_settings()
    })

def news(request):
    news = News.objects.all()
    featured = news.filter(is_featured=True).order_by('-id').first()
    tag = request.GET.get("tag")
    if tag:
        news = news.filter(tags__in=[tag])


    return TemplateResponse(request, 'frontend/news.html', 
        {
            "newss": news[:4],
            "featured": featured,
            "settings":  get_settings()
        }
    )

def news_detail(request, slug):
    news = News.objects.get(slug=slug)
    taglist = news.tags.all().values_list('id', flat=True)

    newss = (
        News.objects.filter(is_active=True)
        .filter(tags__id__in = taglist)
        .exclude(slug=slug).order_by('-id')
    )

    related_videos = (
        Videos.objects.filter(is_active=True)
        .filter(tags__id__in = taglist)
        .exclude(slug=slug).order_by('-id')
    )

    return TemplateResponse(request, 'frontend/news-detail.html', {
        "news": news, 
        "newss": newss, 
        'related_videos': related_videos,
        "settings":  get_settings(news)
    })


def campaign_detail(request, slug):
    campaign = Campaign.objects.get(slug=slug)
    return TemplateResponse(request, 'frontend/campaign-detail.html', {
        "campaign": campaign, 
    })



def videos(request):
    tag = request.GET.get("tag")
    videos = Videos.objects.all()
    featured = videos.filter(is_featured=True).order_by('-id').first()
    related_videos = (
        Videos.objects.filter(is_active=True)
    )
    if tag:
        videos = videos.filter(tags__in=[tag])
    return TemplateResponse(request, 'frontend/videos.html', 
        {
            "videos": videos,
            "featured": featured,
            "settings":  get_settings(),
            "related_videos": related_videos
        }
    )

def videos_detail(request, slug):
    video = Videos.objects.get(slug=slug)
    taglist = video.tags.all().values_list('id', flat=True)

    related_news = (
        News.objects.filter(is_active=True)
        .filter(tags__id__in = taglist)
        .exclude(slug=slug).order_by('-id')
    )

    related_videos = (
        Videos.objects.filter(is_active=True)
        .filter(tags__id__in = taglist)
        .exclude(slug=slug).order_by('-id')
    )

    return TemplateResponse(request, 'frontend/video-detail.html', {
        "video": video, 
        "newss": related_news, 
        'related_videos': related_videos,
        "settings":  get_settings(video)
    })


def gallery_detail(request, slug):
    page = request.GET.get('page')
    album = Album.objects.get(slug=slug)
    photos = album.photo_set.all()
    results_per_page = 9
    paginator = Paginator(photos, results_per_page)
    try:
        photos = paginator.page(page)
    except PageNotAnInteger:
        photos = paginator.page(1)
    except EmptyPage:
        photos = []

    return TemplateResponse(request, 'frontend/gallery-detail.html', {
        "album": album,
        "photos": photos, 
        "settings":  get_settings()
    })


def publications(request):
    publications = Publication.objects.filter(is_active=True).all()
    
    page = request.GET.get('page')
    results_per_page = 10
    paginator = Paginator(publications, results_per_page)
    try:
        publications = paginator.page(page)
    except PageNotAnInteger:
        publications = paginator.page(1)
    except EmptyPage:
        publications = []

    return TemplateResponse(request, 'frontend/publications.html', 
        {
            "publications": publications,
            "settings":  get_settings()
        }
    )

def search(request):
    query = request.GET.get("query")
    videos = Videos.objects.filter(Q(title__icontains=query)|Q(long_desc__icontains=query)).filter(is_active=True).all()
    newss = News.objects.filter(Q(title__icontains=query)|Q(long_desc__icontains=query)).filter(is_active=True).all()
    publications = Publication.objects.filter(Q(title__icontains=query)|Q(long_desc__icontains=query)).filter(is_active=True).all()
    datas = []
    for video in videos:
        datas.append(video)
    for news in newss:
        datas.append(news)
    for pub in publications:
        datas.append(pub)

    return TemplateResponse(request, 'frontend/search_result.html', 
        {
            "datas": datas,
            "nodata": len(datas) == 0,
            "settings":  get_settings()
        }
    )


def gallery(request):
    albums = Album.objects.filter(is_active=True).all();
    page = request.GET.get('page')
    results_per_page = 9
    paginator = Paginator(albums, results_per_page)
    try:
        albums = paginator.page(page)
    except PageNotAnInteger:
        albums = paginator.page(1)
    except EmptyPage:
        albums = []

    featured = Photo.objects.filter(is_featured=True).order_by('-id').first()
    featured_photos = Photo.objects.filter(is_featured=True).order_by('-id').all()
    return TemplateResponse(request, 'frontend/gallery.html', 
        {
            "albums": albums,
            "featured": featured,
            "featured_photos": featured_photos,
            "settings":  get_settings()
        }
    )

def get_settings(data=None):
    settings = Settings.objects.all()
    serialize_settings_dict={}
    for setting in settings:
        serialize_settings_dict[setting.name] = serialize_settings(setting)
    
    if data is not None:
        serialize_settings_dict['seo_title']['text_value'] = data.title
        serialize_settings_dict['seo_description']['text_value'] = data.short_desc 
        serialize_settings_dict['seo_keywords']['text_value'] = data.short_desc
        serialize_settings_dict['seo_image']['img_value'] = data.img.url

    return serialize_settings_dict


@csrf_exempt
def lazy_load_news(request):
    page = request.POST.get('page')
    news = News.objects.filter(is_active=True).all().order_by('-id')
    results_per_page = 4
    paginator = Paginator(news, results_per_page)
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(2)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    # build a html blogs list with the paginated blogs
    news_html = loader.render_to_string(
        'frontend/news-list.html',
        {'newss': news}
    )
    output_data = {
        'news_html': news_html,
        'has_next': news.has_next()
    }
    return JsonResponse(output_data)


@csrf_exempt
def search_publication(request):
    years = request.POST.get('years')
    years = years.split()
    yearint = []
    for year in years:
        try:
            yearint.append(int(year))
        except:
            pass
    publications = Publication.objects.filter(date__year__in=yearint).order_by('-id')
    
    pubs_html = loader.render_to_string(
        'frontend/pub-list.html',
        {'publications': publications}
    )
    output_data = {
        'pubs_html': pubs_html,
        'count': publications.count(),
    }
    return JsonResponse(output_data)


@csrf_exempt
def subscribe(request):
    email = request.POST.get('email')
    # try :
    Subscribe.objects.create(email=email)
    # except:
    #     pass
    return JsonResponse({"status": "OK"})

@csrf_exempt
def lazy_load_photo(request, id):
    album = Album.objects.filter(id=id).first()
    photos = album.photo_set.all().order_by('-id')
    page = request.POST.get('page')
    results_per_page = 4
    paginator = Paginator(photos, results_per_page)
    has_next = False
    try:
        photos = paginator.page(page)
        has_next = photos.has_next()
    except PageNotAnInteger:
        photos = paginator.page(2)
        has_next = photos.has_next()
    except EmptyPage:
        photos = []

    photos_html = loader.render_to_string(
        'frontend/photos_list.html',
        {'photos': photos}
    )
    output_data = {
        'photos_html': photos_html,
        'has_next': has_next
    }
    return JsonResponse(output_data)

rwi/templates/frontend/index.html
{% extends 'frontend/base.html' %}
{% load humanize %}
{% load static %}
{% load templatehelpers %}


{% block extra_header %}
<link type="text/css" rel="stylesheet" href="{% static 'node_modules/nanogallery2/dist/css/nanogallery2.min.css' %}" />
{% endblock %}

{% block content %}

<section id="slider">
  <div id="slider-animation" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      {% for banner in banners %}

       <div id="carousel-item" 
        findout-url="{{ banner.find_out_url }}"
        video-url="{{ banner.video_url }}"
        class="carousel-item {% if forloop.first %} active {% endif %}"
        style="background-image: url('{{ banner.img.url }}'); height: 650px; 
               background-size: cover; background-position: center; cursor: pointer;">
        <div class="text-box">
          <div class="row align-items-center">
            <div class="col-md-8">
              {% if banner.hastag %}
              <h5 data-wow-duration="1s">#{{ banner.hastag }}</h5>
              {% endif %}
              {% if banner.big_text %}
              <h2 class="wow fadeInUp" data-wow-duration="1s">{{ banner.big_text }}</h2>
              {% endif %}
              {% if banner.small_text %}
              <p class="wow fadeInUp" data-wow-duration="1s">{{ banner.small_text }}</p>
              {% endif %}
            </div>
          </div>
          <div class="wow fadeInUp button-wrapper" data-wow-duration="2s">
            {% if banner.video_url %}
            <a href="" class="button button-white" target="blank">Play Video</a>
            {% endif %}
          </div>
        </div>
      </div>
      {% endfor %}

    </div>
    <div class="slider-arrow">
      <a class="Prev" href="#slider-animation" data-slide="prev">
        <i class="fa fa-arrow-circle-left"></i>
      </a>
      &nbsp;&nbsp;&nbsp;
      <a class="Next" href="#slider-animation" data-slide="next">
        <i class="fa fa-arrow-circle-right"></i>
      </a>
    </div>
  </div>
</section>

<section class="who-we-are">
  <div class="who-we-are-wrapper">
    <div class="row who-we-are-content">
      <div class="col-md-6 col-sm-12 who-we-are-left">
        <img src="{% static 'images/raoullogo.png' %}" />
        <h4 class="big-title" style="margin-top: 20px;">
          <mark>RWI’s Regional Asia and Pacific Programme (RAPP)</mark> specifically supports the stronger alignment of
          environmental and human rights outcomes – and recognises the inherent interaction and mutual reliance between
          these two focus areas.
          <br /><br />Through support by the Swedish International Development Cooperation (SIDA), RWI is actively
          promoting and highlighting how intrinsic human rights are to responses to climate change and the environment.
          <!-- <p class="description">Our Campaign</p>
          <p class="description-2">People on the move</p>
          <p class="description-2">Inclusive societies</p>
          <p class="description-2">Economic globalization and Human rights</p> -->
          <div style="margin-top: 30px;">
            <p><a href="https://rwi.or.id/who-we-are" class="button button-blue">LEARN MORE ABOUT RWI</a></p>
            <div class="button-wrapper">
              <a href="https://rwi.or.id/contacts" class="button button-blue">CONTACT RWI</a>
              <div class="socmed-wrapper">
                <a href="{{ settings.url_facebook.text_value }}" target="_blank"><i class="fa fa-facebook"></i></a>
                &nbsp;
                <a href="{{ settings.url_twitter.text_value }}" target="_blank"><i class="fa fa-twitter"></i></a> &nbsp;
                <a href="{{ settings.url_instagram.text_value }}" target="_blank"><i class="fa fa-instagram"></i></a>
                &nbsp;
                <a href="{{ settings.url_youtube.text_value }}" target="_blank"><i class="fa fa-youtube"></i></a> &nbsp;
              </div>
            </div>
          </div>
      </div>

      <div class="col-md-6 col-sm-12 who-we-are-right">
        <img class="" src="{% static 'images/whowearebg22.png' %}">
        <a href="{% url 'frontend:campaign' %}" class="button button-blue">VIEW CAMPAIGNS</a>
      </div>
    </div>
  </div>
</section>

<section class="video-wrapper">
  <div class="content-video-wrapper">
    <p class="sub-header header-video">Latest Video</p>
    <div class="content-video">
      {% for video in latest_videos|slice:"0:2" %}
      <div class="item">
        <a href="{% url 'frontend:videos_detail' video.slug %}">
          <div style="position: relative; ">
            <img class="download-button medium" src="{% static 'images/download.png' %}" />
            <img class="img-item" src="{{ video.img.url }}" />
          </div>
        </a>
        <div class="title-wrapper">
          <p class="title">{{ video.title | truncatewords:"22" }}</p>
        </div>
        <p class="description"><span class="time">{{ video.time }} </span>&nbsp; Posted {{ video.date }} </p>
      </div>
      {% endfor %}
    </div>
  </div>
</section>

<section class="news-wrapper">
  <div class="content-news-wrapper">
    <p class="sub-header header-news">Latest News</p>
    <div class="content-news">
      {% for news in latest_news|slice:"0:3" %}
      <div class="item">
        <img class="img-item" src="{{news.img.url}}" />
        <div class="item-content">
          <p class="title">{{ news.title}}</p>
          <p class="description">{{news.short_desc|truncatewords:"30" }}<br>
          </p>
          <p class="date">{{news.date}}</p>
          <a href="{% url 'frontend:news_detail' news.slug %}" class="read-more">READ MORE</a>
        </div>
      </div>
      {% endfor %}

    </div>
  </div>
</section>

<section class="featur-video">
  <div class="content-feature-video">
    <div class="content">
      <div class="left">
        <a href="{% url 'frontend:videos_detail' f_video.slug %}">
          <div style="position: relative; height: 100%;">
            <img class="download-button medium" src="{% static 'images/download.png' %}" />
            <img class="img-item" src="{{f_video.img.url}}" />
          </div>
        </a>
      </div>
      <div class="right">
        <p class="sub-header header-feature-video">Featured Video</p>
        <p><span class="time">{{ f_video.time }} </span></p>
        <p class="title">{{ f_video.title }}</p>
        <div class="description">{{ f_video.long_desc | safe|truncatewords:"70"|linebreaks }}</div>
        <p class="date">Posted {{ f_video.date }}</p>
        <a class="share" href="#">Share Video</a>
      </div>
    </div>
  </div>
</section>

<section class="rwi-link">
  <div class="content-rwi-link">
    <div class="content">
      <div class="item">
        <img class="img-item" src="{% static 'images/rwi_videos.png' %}" />
        <h3>RWI Videos</h3>
        <p>Discover and Visit RWI's Video Here</p>
        <a href="/videos/" class="button">VISIT LINK</a>
      </div>

      <div class="item">
        <img class="img-item" src="{% static 'images/rwi_news.png' %}" />
        <h3>RWI News and Blogs</h3>
        <p>Discover and Visit RWI's Video Here</p>
        <a href="/news/" class="button">VISIT LINK</a>
      </div>

      <div class="item">
        <img class="img-item" src="{% static 'images/rwi_gallery.png' %}" />
        <h3>RWI Gallery</h3>
        <p>Discover and Visit RWI's Video Here</p>
        <a href="/gallery/" class="button">VISIT LINK</a>
      </div>
    </div>
  </div>
</section>

<section class="photos">
  <div>
    <div id="nanogallery2" data-nanogallery2='{ 
          "viewerTools":     {
            "topLeft":    "pageCounter",
            "topRight":   "closeButton"
          },
          "thumbnailWidth":   "auto",
          "thumbnailHeight":  "180",
          "galleryMosaic" :   [
            { "w": 2, "h": 2, "c": 1, "r": 1 },
            { "w": 1, "h": 1, "c": 3, "r": 1 },
            { "w": 1, "h": 1, "c": 3, "r": 2 },
            { "w": 1, "h": 2, "c": 4, "r": 1 },
            { "w": 2, "h": 1, "c": 5, "r": 1 }
          ]
        }'>
      {% for photo in featured_photos %}
      <a href="{{ photo.img.url }}" data-ngthumb="{{ photo.img.url }}"></a>
      {% endfor %}
    </div>

  </div>
  <div class="see-all">
    <img class="icon-cam" src="{% static 'images/icon-cam.png' %}" />
    <div>
      <h5 class="thousand-text">Photos that tell a <span class="thousand-text">thousand stories</span></h5>
      <p>{{ settings.photos_description.text_value|safe }}</p>
      <a href="/gallery/" class="button button-blue" style="margin-top: 10px;">SEE ALL PHOTOS</a>
    </div>
  </div>

  <div class="join-movement">
    <div class="content-movement">
      <p>{{ settings.join_movement.text_value|safe }}</p>
      <h3>{{ settings.join_movement_description.text_value|safe }}</h3>
      <h2>#{{ settings.join_movement_hashtag.text_value|safe }}</h2>
    </div>
    <img class="people-photos-mobile" src="{% static 'images/people.png' %}" style="width: 100%;" />
  </div>

  <img class="people-photos" src="{% static 'images/people.png' %}" style="width: 100%;" />
</section>

{% endblock content %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'node_modules/nanogallery2/dist/jquery.nanogallery2.min.js' %}"></script>
<script>
  $(document).ready(function () {
    $(document).on('click','#carousel-item', function(e){
      if (e.target.tagName == "DIV") {
        window.open(this.getAttribute('findout-url'), '_blank');
      }
      else if (e.target.tagName == "A") {
        window.open(this.getAttribute('video-url'), '_blank');
      }
    })
  })
</script>
{% endblock %}

rwi/templates/frontend/news-list.html
{% load templatehelpers %}
{% for news in newss %}
  {% if forloop.counter|mod:4 == 0 %}
  <div class="col-md-12 item-big">
    <div class="inner-item">
      <div class="left">
        <img class="img-item" src="{{ news.img.url }}" />
      </div>
      <div class="right">
        <p class="description">{{ news.date }}</p>
        <p class="title">{{ news.title }}</p>
        <p class="description">{{news.short_desc|safe|truncatewords:"60"|linebreaks}}</p>
        <a href="{% url 'frontend:news_detail' news.slug %}" href="" class="button">Read More</a>
      </div>
    </div>
  </div>
  {% else %}
  <div class="col-md-4 col-sm-12 item">
    <div class="inner-item">
      <img class="img-item" src="{{ news.img.url }}" />
      <div class="item-content">
        <p class="title">{{news.title}}</p>
        <p class="description">{{news.short_desc|safe|truncatewords:"60"|linebreaks}}</p>
        <p class="date">{{news.date}}</p>
        <a href="{% url 'frontend:news_detail' news.slug %}" class="read-more">READ MORE</a>
      </div>
    </div>
  </div>
  {% endif %}
{% endfor %}

rwi/templates/frontend/pub-list.html
{% load humanize %}
{% load templatehelpers %}
{% load static %}

{% for pub in publications %}
<div class="pub-item">
  <div class="img-wrapper">
    <img src="{{ pub.img.url }}" />
  </div>
  <div class="text">
    <h5>{{ pub.title }}</h5>
    <p>{{ pub.short_desc }} . {{ pub.date }}</p>
    <p>{{ pub.long_desc | safe }}</p>
    <a href="{{ pub.file.url }}" download>
      <img src="{% static 'images/download_paper.png' %}" />
    </a>
  </div>
</div>
{% endfor %}